version: '3'

services:
    backend:
        build:
            context: backend
        volumes:
            - database:/usr/src/app/db
    frontend:
        build:
            context: frontend
        depends_on:
            - backend
    nginx:
        build:
            context: nginx
        ports:
            - 8443:8443
        depends_on:
            - backend
            - frontend

volumes:
    database:
