version: '3'
services:
    backend:
        image: mprooms/backend:$MPROOMS_VERSION
        volumes:
            - database:/usr/src/app/db
    frontend:
        image: mprooms/frontend:$MPROOMS_VERSION
        depends_on:
            - backend
    nginx:
        image: mprooms/nginx:$MPROOMS_VERSION
        depends_on:
            - backend
            - frontend
    gatekeeper:
        image: keycloak/keycloak-gatekeeper
        depends_on:
            - nginx
        ports:
            - "8443:8443"
        command:
            - "--client-id=${GATEKEEPER_CLIENT_ID}"
            - "--client-secret=${GATEKEEPER_CLIENT_SECRET}"
            - "--discovery-url=${GATEKEEPER_DISCOVERY_URL}"
            - "--listen=0.0.0.0:8443"
            - "--redirection-url=https://${HOST_FQDN}"
            - "--upstream-url=http://nginx:8443"
            - "--scopes=openid,profile,email"
            - "--add-claims=name"
            - "--add-claims=upn"

volumes:
    database:
